
version: "3"
services:
  emily-movie-reviews-33s7de-prod:
    image: emily-movie-reviews-33s7de-prod
    container_name: emily-movie-reviews-33s7de-prod
    command: python3 api.py -e ".prod.env"
    restart: always
    ports:
      - 4242:4242
    networks:
      - emily-movie-reviews-33s7de-prod-network
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace:cached
      - ./review_data:/workspace/data

    runtime: runc
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
    ipc: private
networks:
  emily-movie-reviews-33s7de-prod-network:
    name: emily-movie-reviews-33s7de-prod-network
    driver: bridge
  
