on: 
  push:
    branches:
      - uc2
name: UC2_Container_Workflow

jobs:
    build-and-deploy:
        defaults:
          run:
            working-directory: ./movie-reviews
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS_UC2 }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_UC2 }}
            username: ${{ secrets.REGISTRY_USERNAME_UC2 }}
            password: ${{ secrets.REGISTRY_PASSWORD_UC2 }}
        # docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/tsi-movie-reviews:${{ github.sha }}
        - run: |
            sh ./deploy.sh
            docker tag emily-movie-reviews-33s7de-prod:latest ${{ secrets.REGISTRY_LOGIN_SERVER_UC2 }}/emily-movie-reviews-33s7de-prod:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER_UC2 }}/emily-movie-reviews-33s7de-prod:latest
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            environment-variables: PORT=4242 IPC=private RUNTIME=runc HOST_IP=0.0.0.0 HOST_PORT=4242 CONTAINER_PORT=4242 NVIDIA_VISIBLE_DEVICES= NVIDIA_DRIVER_CAPABILITIES= COMPOSE_PROJECT_NAME=emily-movie-reviews-33s7de PYTHONPATH=./ MAIN=api.py
            ports: 4242
            resource-group: ${{ secrets.RESOURCE_GROUP_UC2 }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP_UC2 }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER_UC2 }}/emily-movie-reviews-33s7de-prod:latest
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_UC2 }}
            registry-username: ${{ secrets.REGISTRY_USERNAME_UC2 }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD_UC2 }}
            command-line: python3 api.py -e ".prod.env"
            name: emily-movie-reviews-33s7de-prod
            location: 'west europe'
